### ISSUE TITLE
Empty block not accepted as valid

### ISSUE THREAD

**Issue by stlutz** [tom95/sandblocks#38]
Saving a method with an empty block is not allowed, even though it is equivalent to `[nil]` and used throughout the trunk image.

**Comment by tom95** [comment]
Could you post a screenshot and an example snippet? I couldn't reproduce it, maybe I misunderstood

**Comment by stlutz** [comment]
https://user-images.githubusercontent.com/24944129/113673367-30fdfd00-96b9-11eb-9f52-1dbe20515950.mp4

**Comment by tom95** [comment]
Ah I see, thank you! This is "intended behavior": as long as there is an unfilled hole, saving is not possible. Deleting the hole, leaving just the empty block fixes the issue. I agree that in this case it's confusing.

I could imagine to simply allow saving while there is a hole on statement level, as these will never produce invalid syntax.

**Comment by stlutz** [comment]
Oh, I see. It is a bit weird. I also noticed that you can't navigate to an empty block unless you click on it which also seems unintuitive to me.

https://user-images.githubusercontent.com/24944129/113674536-91da0500-96ba-11eb-9996-8246d999123e.mp4

**Comment by tom95** [comment]
Thanks again for the reports. Your second comment should be addressed in the future via this: https://github.com/tom95/sandblocks/issues/39

The other issue is now fixed: holes on statement level no longer report themselves as invalid.
