### ISSUE TITLE
Bug: Pressing Alt + Arrow Down in browser editor raises nil DNU 

### ISSUE THREAD

**Issue by LinqLover** [tom95/sandblocks#78]
<details><summary>Bug report</summary><pre><code>6 January 2022 5:43:42.452403 pm

VM: Win32 - Smalltalk
Image: Squeak6.0alpha [latest update: #20966]

SecurityManager state:
Restricted: false
FileAccess: true
SocketAccess: true
Working Dir C:\Users\Christoph\OneDrive\Dokumente\Studium\S21_SS\Sonic Thinking\project\squeak
Trusted Dir C:\Users\Christoph\OneDrive\Dokumente\Studium\S21_SS\Sonic Thinking\project\squeak\Christoph
Untrusted Dir C:\Users\Christoph\OneDrive\Dokumente\My Squeak

UndefinedObject(Object)>>doesNotUnderstand: #childSandblocks
	Receiver: nil
	Arguments and temporary variables: 
		aMessage: 	childSandblocks
		exception: 	MessageNotUnderstood: UndefinedObject>>childSandblocks
		resumeValue: 	nil
	Receiver's instance variables: 
nil

SBBrowserEditor(SBBlock)>>closestAdjacentFrom:to:
	Receiver: a SBBrowserEditor(1153585)
	Arguments and temporary variables: 
		mySide: 	#bottomCenter
		theirSide: 	#topCenter
		direction: 	#>
		component: 	#y
		candidates: 	nil
		myPoint: 	1081@740
	Receiver's instance variables: 
		bounds: 	736@520 corner: 1426@740
		owner: 	a PluggablePanelMorph(903934)
		submorphs: 	{a SBRow(1626162) . a SBRow(2359614)}
		fullBounds: 	734@518 corner: 1428@742
		color: 	Color transparent
		extension: 	a MorphExtension (829323) [other:  (actionMap -> an IdentityDictiona...etc...
		decorators: 	an OrderedCollection()
		colorPolicyCache: 	nil
		copyBuffer: 	nil
		copyBufferPreview: 	nil
		modeLabel: 	nil
		selectionLabel: 	nil
		scroll: 	a SBEditorScrollPane(1302432)
		colorPolicy: 	a SBTextColorPolicy
		bottomPanel: 	nil
		compileTime: 	#compileOnSave
		errors: 	a SBErrorPanel(1707804)
		searchInput: 	text bubble
		helpOverlay: 	nil
		globalShortcutListeners: 	an OrderedCollection(a SBBrowserEditor(1153585) text b...etc...
		inputMapping: 	a SBTextInputMapping
		ignoreNext: 	nil
		paletteContainer: 	a SBUpdatingPaletteContainer(1455312)
		history: 	a SBHistoryStack
		dragHelper: 	nil
		cursor: 	a SBBlockCursor(2451613)
		hoverHighlight: 	a SBHoverDecorator
		suggestAlways: 	nil
		activePlugins: 	an OrderedCollection(a SBStLivePreview(775225))
		model: 	a BPBrowser
		fillHorizontal: 	true
		fillVertical: 	false

SBStMessagePart(SBBlock)>>selectToplevelTowards:
	Receiver: message part exampleIconForClass:
	Arguments and temporary variables: 
		aSideSymbol: 	#bottom
		opposite: 	#top
	Receiver's instance variables: 
		bounds: 	100@6 corner: 250@20
		owner: 	a SBStSignature(3590610)
		submorphs: 	{a SBOwnTextMorph(1162899)}
		fullBounds: 	98@4 corner: 252@22
		color: 	Color transparent
		extension: 	a MorphExtension (3473425) [other:  (layoutProperties -> (TableLayou...etc...
		decorators: 	an OrderedCollection()
		colorPolicyCache: 	a SBTextColorPolicy
		text: 	a SBOwnTextMorph(1162899)

SBStMessagePart(SBBlock)>>selectBottomToplevel
	Receiver: message part exampleIconForClass:
	Arguments and temporary variables: 

	Receiver's instance variables: 
		bounds: 	100@6 corner: 250@20
		owner: 	a SBStSignature(3590610)
		submorphs: 	{a SBOwnTextMorph(1162899)}
		fullBounds: 	98@4 corner: 252@22
		color: 	Color transparent
		extension: 	a MorphExtension (3473425) [other:  (layoutProperties -> (TableLayou...etc...
		decorators: 	an OrderedCollection()
		colorPolicyCache: 	a SBTextColorPolicy
		text: 	a SBOwnTextMorph(1162899)

SBStMessagePart(SBBlock)>>performAction:
	Receiver: message part exampleIconForClass:
	Arguments and temporary variables: 
		aSymbol: 	#selectBottomToplevel
		obj: 	message part exampleIconForClass:
	Receiver's instance variables: 
		bounds: 	100@6 corner: 250@20
		owner: 	a SBStSignature(3590610)
		submorphs: 	{a SBOwnTextMorph(1162899)}
		fullBounds: 	98@4 corner: 252@22
		color: 	Color transparent
		extension: 	a MorphExtension (3473425) [other:  (layoutProperties -> (TableLayou...etc...
		decorators: 	an OrderedCollection()
		colorPolicyCache: 	a SBTextColorPolicy
		text: 	a SBOwnTextMorph(1162899)

SBBrowserEditor(SBEditor)>>performForSelection:
	Receiver: a SBBrowserEditor(1153585)
	Arguments and temporary variables: 
		anActionSymbol: 	#selectBottomToplevel
	Receiver's instance variables: 
		bounds: 	736@520 corner: 1426@740
		owner: 	a PluggablePanelMorph(903934)
		submorphs: 	{a SBRow(1626162) . a SBRow(2359614)}
		fullBounds: 	734@518 corner: 1428@742
		color: 	Color transparent
		extension: 	a MorphExtension (829323) [other:  (actionMap -> an IdentityDictiona...etc...
		decorators: 	an OrderedCollection()
		colorPolicyCache: 	nil
		copyBuffer: 	nil
		copyBufferPreview: 	nil
		modeLabel: 	nil
		selectionLabel: 	nil
		scroll: 	a SBEditorScrollPane(1302432)
		colorPolicy: 	a SBTextColorPolicy
		bottomPanel: 	nil
		compileTime: 	#compileOnSave
		errors: 	a SBErrorPanel(1707804)
		searchInput: 	text bubble
		helpOverlay: 	nil
		globalShortcutListeners: 	an OrderedCollection(a SBBrowserEditor(1153585) text b...etc...
		inputMapping: 	a SBTextInputMapping
		ignoreNext: 	nil
		paletteContainer: 	a SBUpdatingPaletteContainer(1455312)
		history: 	a SBHistoryStack
		dragHelper: 	nil
		cursor: 	a SBBlockCursor(2451613)
		hoverHighlight: 	a SBHoverDecorator
		suggestAlways: 	nil
		activePlugins: 	an OrderedCollection(a SBStLivePreview(775225))
		model: 	a BPBrowser
		fillHorizontal: 	true
		fillVertical: 	false

[] in SBBrowserEditor(SBEditor)>>performShortcutFor:
	Receiver: a SBBrowserEditor(1153585)
	Arguments and temporary variables: 
		anEvent: 	[932@538 keystroke '<Opt-Cmd-down>' (31) 284597369]
		action: 	#selectBottomToplevel
	Receiver's instance variables: 
		bounds: 	736@520 corner: 1426@740
		owner: 	a PluggablePanelMorph(903934)
		submorphs: 	{a SBRow(1626162) . a SBRow(2359614)}
		fullBounds: 	734@518 corner: 1428@742
		color: 	Color transparent
		extension: 	a MorphExtension (829323) [other:  (actionMap -> an IdentityDictiona...etc...
		decorators: 	an OrderedCollection()
		colorPolicyCache: 	nil
		copyBuffer: 	nil
		copyBufferPreview: 	nil
		modeLabel: 	nil
		selectionLabel: 	nil
		scroll: 	a SBEditorScrollPane(1302432)
		colorPolicy: 	a SBTextColorPolicy
		bottomPanel: 	nil
		compileTime: 	#compileOnSave
		errors: 	a SBErrorPanel(1707804)
		searchInput: 	text bubble
		helpOverlay: 	nil
		globalShortcutListeners: 	an OrderedCollection(a SBBrowserEditor(1153585) text b...etc...
		inputMapping: 	a SBTextInputMapping
		ignoreNext: 	nil
		paletteContainer: 	a SBUpdatingPaletteContainer(1455312)
		history: 	a SBHistoryStack
		dragHelper: 	nil
		cursor: 	a SBBlockCursor(2451613)
		hoverHighlight: 	a SBHoverDecorator
		suggestAlways: 	nil
		activePlugins: 	an OrderedCollection(a SBStLivePreview(775225))
		model: 	a BPBrowser
		fillHorizontal: 	true
		fillVertical: 	false

[] in SBTextInputMapping(SBInputMapping)>>actionFor:mode:do:ifNone:
	Receiver: a SBTextInputMapping
	Arguments and temporary variables: 
		anEvent: 	[932@538 keystroke '<Opt-Cmd-down>' (31) 284597369]
		aMode: 	#input
		aBlock: 	[closure] in SBBrowserEditor(SBEditor)>>performShortcutFor:
		anotherBlock: 	[closure] in SBBrowserEditor(SBEditor)>>performShortcutFor:
		shortcut: 	SBShortcut(Opt down)
		action: 	#selectBottomToplevel
		ret: 	nil
	Receiver's instance variables: 
		editor: 	nil
		registerBlock: 	[closure] in SBTextInputMapping(SBInputMapping)>>actionFor:mode:do:ifNone:...etc...
		extraShortcuts: 	an OrderedCollection()

SBTextInputMapping(SBInputMapping)>>shortcut:do:
	Receiver: a SBTextInputMapping
	Arguments and temporary variables: 
		aShortcut: 	SBShortcut(Opt down)
		aSymbol: 	#selectBottomToplevel
	Receiver's instance variables: 
		editor: 	nil
		registerBlock: 	[closure] in SBTextInputMapping(SBInputMapping)>>actionFor:mode:do:ifNone:...etc...
		extraShortcuts: 	an OrderedCollection()

SBTextInputMapping(SBInputMapping)>>registerShortcut:do:
	Receiver: a SBTextInputMapping
	Arguments and temporary variables: 
		aShortcut: 	SBShortcut(Opt down)
		aSymbol: 	#selectBottomToplevel
	Receiver's instance variables: 
		editor: 	nil
		registerBlock: 	[closure] in SBTextInputMapping(SBInputMapping)>>actionFor:mode:do:ifNone:...etc...
		extraShortcuts: 	an OrderedCollection()

SBTextInputMapping>>registerDefaultShortcuts
	Receiver: a SBTextInputMapping
	Arguments and temporary variables: 

	Receiver's instance variables: 
		editor: 	nil
		registerBlock: 	[closure] in SBTextInputMapping(SBInputMapping)>>actionFor:mode:do:ifNone:...etc...
		extraShortcuts: 	an OrderedCollection()

SBTextInputMapping(SBInputMapping)>>registerAllShortcuts
	Receiver: a SBTextInputMapping
	Arguments and temporary variables: 

	Receiver's instance variables: 
		editor: 	nil
		registerBlock: 	[closure] in SBTextInputMapping(SBInputMapping)>>actionFor:mode:do:ifNone:...etc...
		extraShortcuts: 	an OrderedCollection()

SBTextInputMapping(SBInputMapping)>>actionFor:mode:do:ifNone:
	Receiver: a SBTextInputMapping
	Arguments and temporary variables: 
		anEvent: 	[932@538 keystroke '<Opt-Cmd-down>' (31) 284597369]
		aMode: 	#input
		aBlock: 	[closure] in SBBrowserEditor(SBEditor)>>performShortcutFor:
		anotherBlock: 	[closure] in SBBrowserEditor(SBEditor)>>performShortcutFor:
	Receiver's instance variables: 
		editor: 	nil
		registerBlock: 	[closure] in SBTextInputMapping(SBInputMapping)>>actionFor:mode:do:ifNone:...etc...
		extraShortcuts: 	an OrderedCollection()

SBBrowserEditor(SBEditor)>>performShortcutFor:
	Receiver: a SBBrowserEditor(1153585)
	Arguments and temporary variables: 
		anEvent: 	[932@538 keystroke '<Opt-Cmd-down>' (31) 284597369]
	Receiver's instance variables: 
		bounds: 	736@520 corner: 1426@740
		owner: 	a PluggablePanelMorph(903934)
		submorphs: 	{a SBRow(1626162) . a SBRow(2359614)}
		fullBounds: 	734@518 corner: 1428@742
		color: 	Color transparent
		extension: 	a MorphExtension (829323) [other:  (actionMap -> an IdentityDictiona...etc...
		decorators: 	an OrderedCollection()
		colorPolicyCache: 	nil
		copyBuffer: 	nil
		copyBufferPreview: 	nil
		modeLabel: 	nil
		selectionLabel: 	nil
		scroll: 	a SBEditorScrollPane(1302432)
		colorPolicy: 	a SBTextColorPolicy
		bottomPanel: 	nil
		compileTime: 	#compileOnSave
		errors: 	a SBErrorPanel(1707804)
		searchInput: 	text bubble
		helpOverlay: 	nil
		globalShortcutListeners: 	an OrderedCollection(a SBBrowserEditor(1153585) text b...etc...
		inputMapping: 	a SBTextInputMapping
		ignoreNext: 	nil
		paletteContainer: 	a SBUpdatingPaletteContainer(1455312)
		history: 	a SBHistoryStack
		dragHelper: 	nil
		cursor: 	a SBBlockCursor(2451613)
		hoverHighlight: 	a SBHoverDecorator
		suggestAlways: 	nil
		activePlugins: 	an OrderedCollection(a SBStLivePreview(775225))
		model: 	a BPBrowser
		fillHorizontal: 	true
		fillVertical: 	false

SBBrowserEditor(SBEditor)>>handle:
	Receiver: a SBBrowserEditor(1153585)
	Arguments and temporary variables: 
		anEvent: 	[932@538 keystroke '<Opt-Cmd-down>' (31) 284597369]
	Receiver's instance variables: 
		bounds: 	736@520 corner: 1426@740
		owner: 	a PluggablePanelMorph(903934)
		submorphs: 	{a SBRow(1626162) . a SBRow(2359614)}
		fullBounds: 	734@518 corner: 1428@742
		color: 	Color transparent
		extension: 	a MorphExtension (829323) [other:  (actionMap -> an IdentityDictiona...etc...
		decorators: 	an OrderedCollection()
		colorPolicyCache: 	nil
		copyBuffer: 	nil
		copyBufferPreview: 	nil
		modeLabel: 	nil
		selectionLabel: 	nil
		scroll: 	a SBEditorScrollPane(1302432)
		colorPolicy: 	a SBTextColorPolicy
		bottomPanel: 	nil
		compileTime: 	#compileOnSave
		errors: 	a SBErrorPanel(1707804)
		searchInput: 	text bubble
		helpOverlay: 	nil
		globalShortcutListeners: 	an OrderedCollection(a SBBrowserEditor(1153585) text b...etc...
		inputMapping: 	a SBTextInputMapping
		ignoreNext: 	nil
		paletteContainer: 	a SBUpdatingPaletteContainer(1455312)
		history: 	a SBHistoryStack
		dragHelper: 	nil
		cursor: 	a SBBlockCursor(2451613)
		hoverHighlight: 	a SBHoverDecorator
		suggestAlways: 	nil
		activePlugins: 	an OrderedCollection(a SBStLivePreview(775225))
		model: 	a BPBrowser
		fillHorizontal: 	true
		fillVertical: 	false

SBBrowserEditor(SBEditor)>>filterEvent:for:
	Receiver: a SBBrowserEditor(1153585)
	Arguments and temporary variables: 
		anEvent: 	[932@538 keystroke '<Opt-Cmd-down>' (31) 284597369]
		aMorph: 	a SBBrowserEditor(1153585)
		helper: 	nil
	Receiver's instance variables: 
		bounds: 	736@520 corner: 1426@740
		owner: 	a PluggablePanelMorph(903934)
		submorphs: 	{a SBRow(1626162) . a SBRow(2359614)}
		fullBounds: 	734@518 corner: 1428@742
		color: 	Color transparent
		extension: 	a MorphExtension (829323) [other:  (actionMap -> an IdentityDictiona...etc...
		decorators: 	an OrderedCollection()
		colorPolicyCache: 	nil
		copyBuffer: 	nil
		copyBufferPreview: 	nil
		modeLabel: 	nil
		selectionLabel: 	nil
		scroll: 	a SBEditorScrollPane(1302432)
		colorPolicy: 	a SBTextColorPolicy
		bottomPanel: 	nil
		compileTime: 	#compileOnSave
		errors: 	a SBErrorPanel(1707804)
		searchInput: 	text bubble
		helpOverlay: 	nil
		globalShortcutListeners: 	an OrderedCollection(a SBBrowserEditor(1153585) text b...etc...
		inputMapping: 	a SBTextInputMapping
		ignoreNext: 	nil
		paletteContainer: 	a SBUpdatingPaletteContainer(1455312)
		history: 	a SBHistoryStack
		dragHelper: 	nil
		cursor: 	a SBBlockCursor(2451613)
		hoverHighlight: 	a SBHoverDecorator
		suggestAlways: 	nil
		activePlugins: 	an OrderedCollection(a SBStLivePreview(775225))
		model: 	a BPBrowser
		fillHorizontal: 	true
		fillVertical: 	false

[] in SBBrowserEditor(Morph)>>sendFilterEvent:for:to:
	Receiver: a SBBrowserEditor(1153585)
	Arguments and temporary variables: 
		anEvent: 	[932@538 keystroke '<Opt-Cmd-down>' (31) 284597369]
		anObject: 	a SBBrowserEditor(1153585)
		filterGroup: 	a WeakArray(a SBBrowserEditor(1153585))
		filteredEvent: 	[932@538 keystroke '<Opt-Cmd-down>' (31) 284597369]
		filterOrNil: 	a SBBrowserEditor(1153585)
		filter: 	a SBBrowserEditor(1153585)
	Receiver's instance variables: 
		bounds: 	736@520 corner: 1426@740
		owner: 	a PluggablePanelMorph(903934)
		submorphs: 	{a SBRow(1626162) . a SBRow(2359614)}
		fullBounds: 	734@518 corner: 1428@742
		color: 	Color transparent
		extension: 	a MorphExtension (829323) [other:  (actionMap -> an IdentityDictiona...etc...
		decorators: 	an OrderedCollection()
		colorPolicyCache: 	nil
		copyBuffer: 	nil
		copyBufferPreview: 	nil
		modeLabel: 	nil
		selectionLabel: 	nil
		scroll: 	a SBEditorScrollPane(1302432)
		colorPolicy: 	a SBTextColorPolicy
		bottomPanel: 	nil
		compileTime: 	#compileOnSave
		errors: 	a SBErrorPanel(1707804)
		searchInput: 	text bubble
		helpOverlay: 	nil
		globalShortcutListeners: 	an OrderedCollection(a SBBrowserEditor(1153585) text b...etc...
		inputMapping: 	a SBTextInputMapping
		ignoreNext: 	nil
		paletteContainer: 	a SBUpdatingPaletteContainer(1455312)
		history: 	a SBHistoryStack
		dragHelper: 	nil
		cursor: 	a SBBlockCursor(2451613)
		hoverHighlight: 	a SBHoverDecorator
		suggestAlways: 	nil
		activePlugins: 	an OrderedCollection(a SBStLivePreview(775225))
		model: 	a BPBrowser
		fillHorizontal: 	true
		fillVertical: 	false

WeakArray(SequenceableCollection)>>do:
	Receiver: a WeakArray(a SBBrowserEditor(1153585))
	Arguments and temporary variables: 
		aBlock: 	[closure] in SBBrowserEditor(Morph)>>sendFilterEvent:for:to:
		index: 	1
		indexLimiT: 	1
	Receiver's instance variables: 
a WeakArray(a SBBrowserEditor(1153585))

SBBrowserEditor(Morph)>>sendFilterEvent:for:to:
	Receiver: a SBBrowserEditor(1153585)
	Arguments and temporary variables: 
		anEvent: 	[932@538 keystroke '<Opt-Cmd-down>' (31) 284597369]
		anObject: 	a SBBrowserEditor(1153585)
		filterGroup: 	a WeakArray(a SBBrowserEditor(1153585))
		filteredEvent: 	[932@538 keystroke '<Opt-Cmd-down>' (31) 284597369]
	Receiver's instance variables: 
		bounds: 	736@520 corner: 1426@740
		owner: 	a PluggablePanelMorph(903934)
		submorphs: 	{a SBRow(1626162) . a SBRow(2359614)}
		fullBounds: 	734@518 corner: 1428@742
		color: 	Color transparent
		extension: 	a MorphExtension (829323) [other:  (actionMap -> an IdentityDictiona...etc...
		decorators: 	an OrderedCollection()
		colorPolicyCache: 	nil
		copyBuffer: 	nil
		copyBufferPreview: 	nil
		modeLabel: 	nil
		selectionLabel: 	nil
		scroll: 	a SBEditorScrollPane(1302432)
		colorPolicy: 	a SBTextColorPolicy
		bottomPanel: 	nil
		compileTime: 	#compileOnSave
		errors: 	a SBErrorPanel(1707804)
		searchInput: 	text bubble
		helpOverlay: 	nil
		globalShortcutListeners: 	an OrderedCollection(a SBBrowserEditor(1153585) text b...etc...
		inputMapping: 	a SBTextInputMapping
		ignoreNext: 	nil
		paletteContainer: 	a SBUpdatingPaletteContainer(1455312)
		history: 	a SBHistoryStack
		dragHelper: 	nil
		cursor: 	a SBBlockCursor(2451613)
		hoverHighlight: 	a SBHoverDecorator
		suggestAlways: 	nil
		activePlugins: 	an OrderedCollection(a SBStLivePreview(775225))
		model: 	a BPBrowser
		fillHorizontal: 	true
		fillVertical: 	false

--- The full stack ---
UndefinedObject(Object)>>doesNotUnderstand: #childSandblocks
SBBrowserEditor(SBBlock)>>closestAdjacentFrom:to:
SBStMessagePart(SBBlock)>>selectToplevelTowards:
SBStMessagePart(SBBlock)>>selectBottomToplevel
SBStMessagePart(SBBlock)>>performAction:
SBBrowserEditor(SBEditor)>>performForSelection:
[] in SBBrowserEditor(SBEditor)>>performShortcutFor:
[] in SBTextInputMapping(SBInputMapping)>>actionFor:mode:do:ifNone:
SBTextInputMapping(SBInputMapping)>>shortcut:do:
SBTextInputMapping(SBInputMapping)>>registerShortcut:do:
SBTextInputMapping>>registerDefaultShortcuts
SBTextInputMapping(SBInputMapping)>>registerAllShortcuts
SBTextInputMapping(SBInputMapping)>>actionFor:mode:do:ifNone:
SBBrowserEditor(SBEditor)>>performShortcutFor:
SBBrowserEditor(SBEditor)>>handle:
SBBrowserEditor(SBEditor)>>filterEvent:for:
[] in SBBrowserEditor(Morph)>>sendFilterEvent:for:to:
WeakArray(SequenceableCollection)>>do:
SBBrowserEditor(Morph)>>sendFilterEvent:for:to:
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
SBBrowserEditor(Morph)>>sendFilterEventCaptureAgain:for:
SBBrowserEditor(Morph)>>sendFilterEventCapture:for:
SBBrowserEditor(Morph)>>processEvent:using:
SBBrowserEditor(Morph)>>processEvent:
[] in MorphicEventDispatcher>>dispatchEvent:toSubmorphsOf:
Array(SequenceableCollection)>>do:
PluggablePanelMorph(Morph)>>submorphsDo:
MorphicEventDispatcher>>dispatchEvent:toSubmorphsOf:
MorphicEventDispatcher>>dispatchEvent:withHandler:withMorph:
MorphicEventDispatcher>>dispatchDefault:with:
MorphicEventDispatcher>>dispatchEvent:with:
PluggablePanelMorph(Morph)>>processEvent:using:
PluggablePanelMorph(Morph)>>processEvent:
[] in MorphicEventDispatcher>>dispatchEvent:toSubmorphsOf:
Array(SequenceableCollection)>>do:
PluggableSystemWindow(Morph)>>submorphsDo:
MorphicEventDispatcher>>dispatchEvent:toSubmorphsOf:
MorphicEventDispatcher>>dispatchEvent:withHandler:withMorph:
MorphicEventDispatcher>>dispatchDefault:with:
MorphicEventDispatcher>>dispatchEvent:with:
PluggableSystemWindow(Morph)>>processEvent:using:
PluggableSystemWindow(Morph)>>processEvent:
[] in MorphicEventDispatcher>>dispatchEvent:toSubmorphsOf:
Array(SequenceableCollection)>>do:
PasteUpMorph(Morph)>>submorphsDo:
MorphicEventDispatcher>>dispatchEvent:toSubmorphsOf:
MorphicEventDispatcher>>dispatchEvent:withHandler:withMorph:
MorphicEventDispatcher>>dispatchDefault:with:
MorphicEventDispatcher>>dispatchEvent:with:
PasteUpMorph(Morph)>>processEvent:using:
[] in PasteUpMorph>>processEvent:using:
[] in ActiveWorldVariable class(DynamicVariable class)>>value:during:
FullBlockClosure(BlockClosure)>>ensure:
ActiveWorldVariable class(DynamicVariable class)>>value:during:
[] in ActiveWorldVariable class>>value:during:
FullBlockClosure(BlockClosure)>>ensure:
ActiveWorldVariable class>>value:during:
PasteUpMorph>>becomeActiveDuring:
PasteUpMorph>>processEvent:using:
PasteUpMorph(Morph)>>processEvent:
[] in [] in [] in HandMorph>>sendEvent:focus:clear:
[] in ActiveEventVariable class(DynamicVariable class)>>value:during:
-- and more not shown --</code></pre></details>

**Comment by tom95** [comment]
Do you still happen to have a screenshot of the configuration of the screen? Seems to depend on the involved morphs/blocks

**Comment by LinqLover** [comment]
This?

![image](https://user-images.githubusercontent.com/38782922/148420039-fe738a3f-c881-4fe7-bf72-7a6338db8680.png)

**Comment by tom95** [comment]
Thank you!
