### ISSUE TITLE
Error during autocompletion 🐈‍⬛ 

### ISSUE THREAD

**Issue by MichaelBuessemeyer** [tom95/sandblocks#83]
The autocompletion seems to throw errors when trying to type the following in a sandblocks workspace:
```smalltalk
|morphy|
morphy := ImageMorph new.
morph image: ...
```
While typing the `image:` message a error pops up with each newly typed character.

Here is an example image with the error with the full stack: 
![image](https://user-images.githubusercontent.com/39529669/149632827-4b9cee4c-f5fd-40ee-ace1-530548b6a2f4.png)

**Comment by tom95** [comment]
Could you try updating squeak via the menu in the very top-left?

**Comment by MichaelBuessemeyer** [comment]
> Could you try updating squeak via the menu in the very top-left?

Jep, that fixed it 🙏
